spring:
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import: optional:file:.env.properties
  application:
    name: clio
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cliodb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 30
        connection:
          provider_disables_autocommit: true
        order_updates: true
        order_inserts: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
r2:
  bucket_name: ${R2_BUCKET_NAME}
  account_id: ${R2_ACCOUNT_ID}
  access_key: ${R2_ACCESS_KEY}
  secret_key: ${R2_SECRET_KEY}

clio:
  master_key: ${EBOOK_MASTER_KEY}
  page_size: 12
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        orm:
#          jdbc:
#            bind: TRACE
#  file:
#    name: app.log
