###
# group: Category
# @name Get Categories

GET http://localhost:8080/api/categories

###
# group: Category
# @name Get Category

GET http://localhost:8080/api/categories/2

###
# group: Category
# @name Create Category

POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "test test"
}

###
# group: Category
# @name Update Category

PATCH http://localhost:8080/api/categories/26
Content-Type: application/json

{
  "name": "testafasdfadsfsfa"
}

###
# group: Category
# @name Delete Category

DELETE http://localhost:8080/api/categories/26
