###
# group: Order
# @name Buy Books

POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "bookIds": [
    27,
    28
  ]
}

###
# group: Order
# @name Buy Subscription

POST http://localhost:8080/api/orders/subscription
Content-Type: application/json

{
  "planId": 1
}
